'use client'

import React, { useState } from 'react'
import Layout from '@/components/Layout'
import Button from '@/components/Button'
import { useProjectContext, UserStoryItem } from '@/context/ProjectContext'
import { userStoryService, UserStoryInput } from '@/services/userStoryService'
import { Sparkles, User, Pencil, Trash2, Plus, X, Loader2 } from 'lucide-react'

const emptyForm: UserStoryInput = { actor: '', goal: '', benefit: '', acceptanceCriteria: '' }

export default function UserStoriesPage() {
  const { selectedProject, selectedProjectId, loading, refreshSelectedProject } = useProjectContext()
  const [showForm, setShowForm] = useState(false)
  const [editingId, setEditingId] = useState<number | null>(null)
  const [form, setForm] = useState<UserStoryInput>(emptyForm)
  const [saving, setSaving] = useState(false)
  const [deletingId, setDeletingId] = useState<number | null>(null)
  const [error, setError] = useState<string | null>(null)

  const userStories: UserStoryItem[] = selectedProject?.userStories ?? []

  const startCreate = () => {
    setEditingId(null)
    setForm(emptyForm)
    setError(null)
    setShowForm(true)
  }

  const startEdit = (story: UserStoryItem) => {
    setEditingId(story.id)
    setForm({
      actor: story.actor ?? '',
      goal: story.goal ?? '',
      benefit: story.benefit ?? '',
      acceptanceCriteria: story.acceptanceCriteria ?? '',
    })
    setError(null)
    setShowForm(true)
  }

  const cancelForm = () => {
    setShowForm(false)
    setEditingId(null)
    setForm(emptyForm)
    setError(null)
  }

  const handleSubmit = async () => {
    if (!selectedProjectId) return
    if (!form.goal.trim()) {
      setError('Goal is required')
      return
    }
    setSaving(true)
    setError(null)
    try {
      if (editingId != null) {
        await userStoryService.update(selectedProjectId, editingId, form)
      } else {
        await userStoryService.create(selectedProjectId, form)
      }
      await refreshSelectedProject()
      cancelForm()
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to save user story')
    } finally {
      setSaving(false)
    }
  }

  const handleDelete = async (story: UserStoryItem) => {
    if (!selectedProjectId) return
    setDeletingId(story.id)
    try {
      await userStoryService.remove(selectedProjectId, story.id)
      await refreshSelectedProject()
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to delete user story')
    } finally {
      setDeletingId(null)
    }
  }

  return (
    <Layout>
      <div className="p-6 space-y-6 max-w-5xl">
        <header className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
          <div>
            <p className="text-xs uppercase tracking-[0.4em] text-slate-400">User Stories</p>
            <h1 className="text-3xl font-semibold text-slate-900">
              {selectedProject ? selectedProject.name : 'User Stories'}
            </h1>
            <p className="text-sm text-slate-500 max-w-2xl">
              Stories generated by AI from your uploaded SRS document, plus any you add manually.
            </p>
          </div>
          <Button size="md" onClick={startCreate} disabled={!selectedProjectId}>
            <Plus className="w-4 h-4 mr-2" />
            Add User Story
          </Button>
        </header>

        {!selectedProjectId && !loading && (
          <div className="rounded-2xl border border-slate-200 bg-white p-6 text-sm text-slate-500 shadow-soft">
            Select or create a project first to view and manage its user stories.
          </div>
        )}

        {selectedProject && selectedProject.status !== 'completed' && (
          <div className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800">
            AI analysis for this project is {selectedProject.status}. Generated stories will appear here once processing completes.
          </div>
        )}

        {error && (
          <div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>
        )}

        {showForm && (
          <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-soft space-y-4">
            <div className="flex items-center justify-between">
              <h2 className="text-lg font-semibold text-slate-900">
                {editingId != null ? 'Edit User Story' : 'New User Story'}
              </h2>
              <button onClick={cancelForm} className="text-slate-400 hover:text-slate-700" aria-label="Close form">
                <X className="w-5 h-5" />
              </button>
            </div>
            <div className="grid gap-4 sm:grid-cols-2">
              <label className="block space-y-2 text-sm text-slate-600">
                <span className="text-xs uppercase tracking-[0.4em] text-slate-400">Actor</span>
                <input
                  value={form.actor}
                  onChange={(e) => setForm((f) => ({ ...f, actor: e.target.value }))}
                  placeholder="e.g. Registered member"
                  className="w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-2 text-sm text-slate-700 focus:border-primary-500 focus:ring-2 focus:ring-primary-500/20"
                />
              </label>
              <label className="block space-y-2 text-sm text-slate-600">
                <span className="text-xs uppercase tracking-[0.4em] text-slate-400">Goal *</span>
                <input
                  value={form.goal}
                  onChange={(e) => setForm((f) => ({ ...f, goal: e.target.value }))}
                  placeholder="e.g. search the catalog by title"
                  className="w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-2 text-sm text-slate-700 focus:border-primary-500 focus:ring-2 focus:ring-primary-500/20"
                />
              </label>
            </div>
            <label className="block space-y-2 text-sm text-slate-600">
              <span className="text-xs uppercase tracking-[0.4em] text-slate-400">Benefit</span>
              <input
                value={form.benefit}
                onChange={(e) => setForm((f) => ({ ...f, benefit: e.target.value }))}
                placeholder="so that I can find books quickly"
                className="w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-2 text-sm text-slate-700 focus:border-primary-500 focus:ring-2 focus:ring-primary-500/20"
              />
            </label>
            <label className="block space-y-2 text-sm text-slate-600">
              <span className="text-xs uppercase tracking-[0.4em] text-slate-400">Acceptance Criteria</span>
              <textarea
                value={form.acceptanceCriteria}
                onChange={(e) => setForm((f) => ({ ...f, acceptanceCriteria: e.target.value }))}
                rows={3}
                className="w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-2 text-sm text-slate-700 focus:border-primary-500 focus:ring-2 focus:ring-primary-500/20"
              />
            </label>
            <div className="flex justify-end gap-3">
              <Button variant="outline" size="md" onClick={cancelForm}>Cancel</Button>
              <Button size="md" onClick={handleSubmit} isLoading={saving}>
                {editingId != null ? 'Save changes' : 'Create story'}
              </Button>
            </div>
          </section>
        )}

        <section className="space-y-4">
          {userStories.length === 0 && !showForm && selectedProjectId && (
            <div className="rounded-2xl border border-slate-200 bg-white p-6 text-sm text-slate-500 shadow-soft">
              No user stories yet. They&apos;ll appear here once AI processing completes, or add one manually above.
            </div>
          )}
          {userStories.map((story) => (
            <div key={story.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-soft space-y-2">
              <div className="flex items-start justify-between gap-3">
                <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.3em]">
                  {story.source === 'ai' ? (
                    <span className="inline-flex items-center gap-1 rounded-full bg-primary-50 text-primary-700 px-3 py-1">
                      <Sparkles className="w-3 h-3" /> AI Generated
                    </span>
                  ) : (
                    <span className="inline-flex items-center gap-1 rounded-full bg-slate-100 text-slate-600 px-3 py-1">
                      <User className="w-3 h-3" /> Manual
                    </span>
                  )}
                </div>
                <div className="flex items-center gap-1">
                  <button
                    onClick={() => startEdit(story)}
                    className="rounded-lg p-2 text-slate-400 hover:bg-slate-100 hover:text-slate-700 transition"
                    aria-label="Edit user story"
                  >
                    <Pencil className="w-4 h-4" />
                  </button>
                  <button
                    onClick={() => handleDelete(story)}
                    disabled={deletingId === story.id}
                    className="rounded-lg p-2 text-slate-400 hover:bg-red-50 hover:text-red-600 transition disabled:opacity-50"
                    aria-label="Delete user story"
                  >
                    {deletingId === story.id ? <Loader2 className="w-4 h-4 animate-spin" /> : <Trash2 className="w-4 h-4" />}
                  </button>
                </div>
              </div>
              <p className="text-sm text-slate-900">
                As a <span className="font-semibold">{story.actor || 'user'}</span>, I want to{' '}
                <span className="font-semibold">{story.goal}</span>
                {story.benefit ? <> so that {story.benefit}</> : null}.
              </p>
              {story.acceptanceCriteria && (
                <div className="rounded-xl bg-slate-50 border border-slate-200 px-4 py-2 text-xs text-slate-600 whitespace-pre-line">
                  <span className="font-semibold text-slate-500 uppercase tracking-[0.3em] text-[10px]">Acceptance Criteria</span>
                  <p className="mt-1">{story.acceptanceCriteria}</p>
                </div>
              )}
            </div>
          ))}
        </section>
      </div>
    </Layout>
  )
}
